import Head from 'next/head'
import Nav from '@/components/Nav'
import Marquee from '@/components/Marquee'
import Boxes from '@/components/Boxes'

export default function Home() {
  return (
    <>
      <Head>
        <title> Prbly </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
  
    <Nav/> 

    <div className="mx-auto flex align-middle max-w-screen-2xl">
        <h1 className="text-7xl leading-tight text-prbly-black mx-auto align-middle p-52 text-center font-Main font-light"> Main title test hello hello title land<br/> title test  hello </h1>
    </div>


    <Marquee />


    <div className="mx-auto flex flex-col max-w-screen-2xl p-40 pb-24">
          <h1 className="text-prbly-main text-base font-Sub mx-auto"> Solutions </h1>
          <h1 className='text-7xl leading-tight font-Main font-thin text-prbly-black mx-auto ml-20'>
            Simple yet effective
          </h1>
          <h1 className='text-7xl leading-tight font-Main font-thin text-prbly-black mx-auto pl-80 mt-5'>
            prbly tagline yes
          </h1>
    </div>

    <Boxes/>

    <br/>
    <br/>
    <br/>
   

    </>
  )
}
