import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title> Prbly </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
  
  
    <div className="mx-auto flex align-middle max-w-screen-2xl">
        <h1 className="text-6xl font-Main text-prbly-black mx-auto align-middle p-60"> Test test test test test test </h1>
    </div>

    </>
  )
}
